module.exports = {
  poolABI: [
    {
      inputs: [
        { internalType: 'address', name: 'riskManager_', type: 'address' },
        { internalType: 'contract ERC20', name: 'asset_', type: 'address' },
        { internalType: 'address', name: 'treasury_', type: 'address' },
        { internalType: 'address', name: 'accountFactory', type: 'address' },
        { internalType: 'address', name: 'liquidator', type: 'address' },
      ],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    { inputs: [], name: 'AmountExceedsBalance', type: 'error' },
    { inputs: [], name: 'AuctionOngoing', type: 'error' },
    { inputs: [], name: 'CoolDownPeriodNotPassed', type: 'error' },
    { inputs: [], name: 'FunctionIsPaused', type: 'error' },
    { inputs: [], name: 'FunctionNotImplemented', type: 'error' },
    { inputs: [], name: 'InvalidVersion', type: 'error' },
    { inputs: [], name: 'IsNotAnAccount', type: 'error' },
    { inputs: [], name: 'IsNotAnAccountWithDebt', type: 'error' },
    { inputs: [], name: 'LiquidationWeightsTooHigh', type: 'error' },
    { inputs: [], name: 'NonExistingTranche', type: 'error' },
    { inputs: [], name: 'OnlyGuardian', type: 'error' },
    { inputs: [], name: 'OpenPositionNonZero', type: 'error' },
    { inputs: [], name: 'TrancheAlreadyExists', type: 'error' },
    { inputs: [], name: 'Unauthorized', type: 'error' },
    { inputs: [], name: 'Unauthorized', type: 'error' },
    { inputs: [], name: 'ZeroAmount', type: 'error' },
    { inputs: [], name: 'ZeroShares', type: 'error' },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'owner',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'spender',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256',
        },
      ],
      name: 'Approval',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'account',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'creditor',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'startDebt',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'initiationReward',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'terminationReward',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'penalty',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'badDebt',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'surplus',
          type: 'uint256',
        },
      ],
      name: 'AuctionFinished',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'account',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'creditor',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint128',
          name: 'openDebt',
          type: 'uint128',
        },
      ],
      name: 'AuctionStarted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'account',
          type: 'address',
        },
        { indexed: true, internalType: 'address', name: 'by', type: 'address' },
        {
          indexed: false,
          internalType: 'address',
          name: 'to',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'fee',
          type: 'uint256',
        },
        {
          indexed: true,
          internalType: 'bytes3',
          name: 'referrer',
          type: 'bytes3',
        },
      ],
      name: 'Borrow',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'account',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'owner',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'beneficiary',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256',
        },
      ],
      name: 'CreditApproval',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'caller',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'owner',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'assets',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'shares',
          type: 'uint256',
        },
      ],
      name: 'Deposit',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'user',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'newGuardian',
          type: 'address',
        },
      ],
      name: 'GuardianChanged',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'uint256',
          name: 'interest',
          type: 'uint256',
        },
      ],
      name: 'InterestSynced',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'tranche',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'uint8',
          name: 'trancheIndex',
          type: 'uint8',
        },
        {
          indexed: false,
          internalType: 'uint16',
          name: 'interestWeight',
          type: 'uint16',
        },
      ],
      name: 'InterestWeightTrancheUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'uint16',
          name: 'liquidationWeight',
          type: 'uint16',
        },
      ],
      name: 'LiquidationWeightTrancheUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'user',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'newOwner',
          type: 'address',
        },
      ],
      name: 'OwnershipTransferred',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'bool',
          name: 'repayPauseFlagsUpdated',
          type: 'bool',
        },
        {
          indexed: false,
          internalType: 'bool',
          name: 'withdrawPauseFlagsUpdated',
          type: 'bool',
        },
        {
          indexed: false,
          internalType: 'bool',
          name: 'borrowPauseFlagsUpdated',
          type: 'bool',
        },
        {
          indexed: false,
          internalType: 'bool',
          name: 'depositPauseFlagsUpdated',
          type: 'bool',
        },
        {
          indexed: false,
          internalType: 'bool',
          name: 'liquidationPauseFlagsUpdated',
          type: 'bool',
        },
      ],
      name: 'PauseFlagsUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'uint256',
          name: 'totalDebt',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'totalLiquidity',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint80',
          name: 'interestRate',
          type: 'uint80',
        },
      ],
      name: 'PoolStateUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'account',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'from',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256',
        },
      ],
      name: 'Repay',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'address',
          name: 'riskManager',
          type: 'address',
        },
      ],
      name: 'RiskManagerUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'address',
          name: 'tranche',
          type: 'address',
        },
      ],
      name: 'TranchePopped',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'from',
          type: 'address',
        },
        { indexed: true, internalType: 'address', name: 'to', type: 'address' },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256',
        },
      ],
      name: 'Transfer',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'uint16',
          name: 'interestWeight',
          type: 'uint16',
        },
        {
          indexed: false,
          internalType: 'uint16',
          name: 'liquidationWeight',
          type: 'uint16',
        },
      ],
      name: 'TreasuryWeightsUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'uint256',
          name: 'accountVersion',
          type: 'uint256',
        },
        { indexed: false, internalType: 'bool', name: 'valid', type: 'bool' },
      ],
      name: 'ValidAccountVersionsUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'caller',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'receiver',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'owner',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'assets',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'shares',
          type: 'uint256',
        },
      ],
      name: 'Withdraw',
      type: 'event',
    },
    {
      inputs: [],
      name: 'DOMAIN_SEPARATOR',
      outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'tranche', type: 'address' },
        { internalType: 'uint16', name: 'interestWeight_', type: 'uint16' },
      ],
      name: 'addTranche',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'allowance',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'spender', type: 'address' },
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
      ],
      name: 'approve',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'beneficiary', type: 'address' },
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'address', name: 'account', type: 'address' },
      ],
      name: 'approveBeneficiary',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'asset',
      outputs: [{ internalType: 'contract ERC20', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'startDebt', type: 'uint256' },
        { internalType: 'uint256', name: 'minimumMargin_', type: 'uint256' },
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'address', name: 'account', type: 'address' },
        { internalType: 'address', name: 'bidder', type: 'address' },
      ],
      name: 'auctionRepay',
      outputs: [{ internalType: 'bool', name: 'earlyTerminate', type: 'bool' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'balanceOf',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'address', name: 'account', type: 'address' },
        { internalType: 'address', name: 'to', type: 'address' },
        { internalType: 'bytes3', name: 'referrer', type: 'bytes3' },
      ],
      name: 'borrow',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'borrowPaused',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'calcUnrealisedDebt',
      outputs: [
        { internalType: 'uint256', name: 'unrealisedDebt', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'guardian_', type: 'address' }],
      name: 'changeGuardian',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
      name: 'closeMarginAccount',
      outputs: [],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
      name: 'convertToAssets',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
      name: 'convertToShares',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'creditAllowance',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'decimals',
      outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'deposit',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'assets', type: 'uint256' },
        { internalType: 'address', name: 'from', type: 'address' },
      ],
      name: 'depositInLendingPool',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'depositPaused',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'trancheIndex', type: 'uint256' },
        { internalType: 'uint256', name: 'assets', type: 'uint256' },
      ],
      name: 'donateToTranche',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'amountBorrowed', type: 'uint256' },
        { internalType: 'address', name: 'account', type: 'address' },
        { internalType: 'address', name: 'actionTarget', type: 'address' },
        { internalType: 'bytes', name: 'actionData', type: 'bytes' },
        { internalType: 'bytes3', name: 'referrer', type: 'bytes3' },
      ],
      name: 'flashAction',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes', name: 'callbackData', type: 'bytes' }],
      name: 'flashActionCallback',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getInterestRateConfig',
      outputs: [
        { internalType: 'uint72', name: '', type: 'uint72' },
        { internalType: 'uint72', name: '', type: 'uint72' },
        { internalType: 'uint72', name: '', type: 'uint72' },
        { internalType: 'uint16', name: '', type: 'uint16' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getLiquidationParameters',
      outputs: [
        { internalType: 'uint16', name: '', type: 'uint16' },
        { internalType: 'uint16', name: '', type: 'uint16' },
        { internalType: 'uint16', name: '', type: 'uint16' },
        { internalType: 'uint16', name: '', type: 'uint16' },
        { internalType: 'uint80', name: '', type: 'uint80' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
      name: 'getOpenPosition',
      outputs: [
        { internalType: 'uint256', name: 'openPosition', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'guardian',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'interestRate',
      outputs: [{ internalType: 'uint80', name: '', type: 'uint80' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      name: 'isValidVersion',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'liquidationPaused',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'owner_', type: 'address' }],
      name: 'liquidityOf',
      outputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'owner_', type: 'address' }],
      name: 'liquidityOfAndSync',
      outputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'maxDeposit',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'maxMint',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
      name: 'maxRedeem',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
      name: 'maxWithdraw',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'mint',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [],
      name: 'name',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'nonces',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'accountVersion', type: 'uint256' },
      ],
      name: 'openMarginAccount',
      outputs: [
        { internalType: 'bool', name: 'success', type: 'bool' },
        { internalType: 'address', name: 'numeraire', type: 'address' },
        { internalType: 'address', name: 'liquidator_', type: 'address' },
        { internalType: 'uint256', name: 'minimumMargin_', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'originationFee',
      outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'owner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'pause',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'pauseTimestamp',
      outputs: [{ internalType: 'uint96', name: '', type: 'uint96' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'owner', type: 'address' },
        { internalType: 'address', name: 'spender', type: 'address' },
        { internalType: 'uint256', name: 'value', type: 'uint256' },
        { internalType: 'uint256', name: 'deadline', type: 'uint256' },
        { internalType: 'uint8', name: 'v', type: 'uint8' },
        { internalType: 'bytes32', name: 'r', type: 'bytes32' },
        { internalType: 'bytes32', name: 's', type: 'bytes32' },
      ],
      name: 'permit',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
      name: 'previewDeposit',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
      name: 'previewMint',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
      name: 'previewRedeem',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
      name: 'previewWithdraw',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'redeem',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
        { internalType: 'address', name: 'account', type: 'address' },
      ],
      name: 'repay',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'repayPaused',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'riskManager',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'accountVersion', type: 'uint256' },
        { internalType: 'bool', name: 'valid', type: 'bool' },
      ],
      name: 'setAccountVersion',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint72', name: 'baseRatePerYear_', type: 'uint72' },
        { internalType: 'uint72', name: 'lowSlopePerYear_', type: 'uint72' },
        { internalType: 'uint72', name: 'highSlopePerYear_', type: 'uint72' },
        {
          internalType: 'uint16',
          name: 'utilisationThreshold_',
          type: 'uint16',
        },
      ],
      name: 'setInterestParameters',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'index', type: 'uint256' },
        { internalType: 'uint16', name: 'interestWeight_', type: 'uint16' },
      ],
      name: 'setInterestWeightTranche',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint16', name: 'initiationWeight_', type: 'uint16' },
        { internalType: 'uint16', name: 'penaltyWeight_', type: 'uint16' },
        { internalType: 'uint16', name: 'terminationWeight_', type: 'uint16' },
        { internalType: 'uint16', name: 'minRewardWeight_', type: 'uint16' },
        { internalType: 'uint80', name: 'maxReward_', type: 'uint80' },
      ],
      name: 'setLiquidationParameters',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint16', name: 'liquidationWeight', type: 'uint16' },
      ],
      name: 'setLiquidationWeightTranche',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint96', name: 'minimumMargin_', type: 'uint96' },
      ],
      name: 'setMinimumMargin',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint8', name: 'originationFee_', type: 'uint8' },
      ],
      name: 'setOriginationFee',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'riskManager_', type: 'address' },
      ],
      name: 'setRiskManager',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'treasury_', type: 'address' }],
      name: 'setTreasury',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint16', name: 'interestWeight_', type: 'uint16' },
        { internalType: 'uint16', name: 'liquidationWeight', type: 'uint16' },
      ],
      name: 'setTreasuryWeights',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'account', type: 'address' },
        { internalType: 'uint256', name: 'startDebt', type: 'uint256' },
        { internalType: 'uint256', name: 'minimumMargin_', type: 'uint256' },
        { internalType: 'address', name: 'terminator', type: 'address' },
      ],
      name: 'settleLiquidationHappyFlow',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'account', type: 'address' },
        { internalType: 'uint256', name: 'startDebt', type: 'uint256' },
        { internalType: 'uint256', name: 'minimumMargin_', type: 'uint256' },
        { internalType: 'address', name: 'terminator', type: 'address' },
      ],
      name: 'settleLiquidationUnhappyFlow',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'skim',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'initiator', type: 'address' },
        { internalType: 'uint256', name: 'minimumMargin_', type: 'uint256' },
      ],
      name: 'startLiquidation',
      outputs: [
        { internalType: 'uint256', name: 'startDebt', type: 'uint256' },
      ],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'symbol',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'totalAssets',
      outputs: [
        { internalType: 'uint256', name: 'totalDebt', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'totalLiquidity',
      outputs: [
        { internalType: 'uint256', name: 'totalLiquidity_', type: 'uint256' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'totalSupply',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256', name: '', type: 'uint256' },
      ],
      name: 'transfer',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256', name: '', type: 'uint256' },
      ],
      name: 'transferFrom',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
      name: 'transferOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'unpause',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bool', name: 'repayPaused_', type: 'bool' },
        { internalType: 'bool', name: 'withdrawPaused_', type: 'bool' },
        { internalType: 'bool', name: 'borrowPaused_', type: 'bool' },
        { internalType: 'bool', name: 'depositPaused_', type: 'bool' },
        { internalType: 'bool', name: 'liquidationPaused_', type: 'bool' },
      ],
      name: 'unpause',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'updateInterestRate',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
      ],
      name: 'withdraw',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: 'assets', type: 'uint256' },
        { internalType: 'address', name: 'receiver', type: 'address' },
      ],
      name: 'withdrawFromLendingPool',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'withdrawPaused',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
  ],
};
