const poolsResponseColumns = [
  'chain',
  'project',
  'symbol',
  'tvlUsd',
  'apyBase',
  'apyReward',
  'apy',
  'rewardTokens',
  'pool',
  'apyPct1D',
  'apyPct7D',
  'apyPct30D',
  'stablecoin',
  'ilRisk',
  'exposure',
  'predictions',
  'poolMeta',
  'mu',
  'sigma',
  'count',
  'outlier',
  'underlyingTokens',
  'il7d',
  'apyBase7d',
  'apyMean30d',
  'volumeUsd1d',
  'volumeUsd7d',
  'apyBaseInception',
  'holderCount',
  'avgPositionUsd',
  'top10Pct',
];

module.exports = poolsResponseColumns;
