const utils = require('../utils');

// Ample vaults are prize-linked-savings ERC4626s. The vault deposits user
// USDC into a yield-source vault (Euler V2 / Morpho) and harvests the yield
// for the lottery prize pool — so the Ample vault's own share price barely
// moves. To represent the gross yield being generated by the strategy, we
// compute apyBase from the underlying yield-source vault's pps evolution
// rather than from the Ample vault itself. (Where the yield source isn't
// known, we fall back to the Ample vault's own pps — typically ~0%.)
const VAULTS = {
  base: {
    address: '0x1688aeb3ec7b23a22e2418fdf5bccc67ecf39c0f',
    symbol: 'USDC',
    underlying: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    underlyingDecimals: 6,
    yieldSource: '0x0a1a3b5f2041f33522c4efc754a7d096f880ee16', // eUSDC-1 Euler V2
  },
  arbitrum: {
    address: '0xd1be1f98991cf69355e468ad15b6d0b6429bcfcb',
    symbol: 'USDC',
    underlying: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    underlyingDecimals: 6,
    yieldSource: '0x44c10da836d2abe881b77bbb0b3dce5f85c0c1cc', // eUSDC-6 Euler V2
  },
  katana: {
    address: '0xe5092ab6b8b0c37b1bec12c606614706063d04e8',
    symbol: 'vbUSDC',
    underlying: '0x203A662b0BD271A6ed5a60EdFbd04bFce608FD36',
    underlyingDecimals: 6,
    yieldSource: '0xE4248e2105508FcBad3fe95691551d1AF14015f7', // gtUSDC Morpho
  },
  monad: {
    address: '0xE89d322b5822D828B8252D3087be8486cC2048Ef',
    symbol: 'AUSD',
    underlying: '0x00000000eFE302BEAA2b3e6e1b18d08D69a9012a',
    underlyingDecimals: 6,
    yieldSource: null,
  },
  hyperliquid: {
    address: '0x00a7ab758367da6a3909b75bd30ccc68e8755809',
    symbol: 'WHYPE',
    underlying: '0x5555555555555555555555555555555555555555',
    underlyingDecimals: 18,
    yieldSource: '0x2900abd73631b2f60747e687095537b673c06a76', // feHYPE Felix
  },
};

const buildPool = async (chain, vault) => {
  try {
    const ampleInfo = await utils.getERC4626Info(vault.address, chain, undefined, {
      assetUnit: '1000000000000000000',
    });

    const apyBase = vault.yieldSource
      ? (await utils.getERC4626Info(vault.yieldSource, chain, undefined, {
          assetUnit: '1000000000000000000',
        })).apyBase
      : ampleInfo.apyBase;

    const { pricesByAddress } = await utils.getPrices([vault.underlying], chain);
    const price = pricesByAddress[vault.underlying.toLowerCase()];
    if (!price) return null;

    const tvlUsd =
      (Number(ampleInfo.tvl) / 10 ** vault.underlyingDecimals) * price;

    return {
      pool: `${vault.address}-${chain}`,
      chain: utils.formatChain(chain),
      project: 'ample',
      symbol: vault.symbol,
      tvlUsd,
      apyBase,
      underlyingTokens: [vault.underlying],
      url: 'https://ample.money/',
      isIntrinsicSource: true,
    };
  } catch (err) {
    console.error(`ample ${chain} error:`, err.message);
    return null;
  }
};

const apy = async () => {
  const pools = await Promise.all(
    Object.entries(VAULTS).map(([chain, vault]) => buildPool(chain, vault))
  );
  return pools.filter(Boolean).filter((p) => utils.keepFinite(p));
};

module.exports = {
  timetravel: false,
  apy,
  url: 'https://ample.money/',
};
