module.exports = {
   boosterABI: [
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_staker",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_minter",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_crv",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_voteOwnership",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_voteParameter",
               "type":"address"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"constructor"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"newArbitrator",
               "type":"address"
            }
         ],
         "name":"ArbitratorUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"user",
               "type":"address"
            },
            {
               "indexed":true,
               "internalType":"uint256",
               "name":"poolid",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"Deposited",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"rewardFactory",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"stashFactory",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"tokenFactory",
               "type":"address"
            }
         ],
         "name":"FactoriesUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"feeDistro",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"bool",
               "name":"active",
               "type":"bool"
            }
         ],
         "name":"FeeInfoChanged",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"feeDistro",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"lockFees",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"feeToken",
               "type":"address"
            }
         ],
         "name":"FeeInfoUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"newFeeManager",
               "type":"address"
            }
         ],
         "name":"FeeManagerUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"lockIncentive",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"stakerIncentive",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"earmarkIncentive",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"platformFee",
               "type":"uint256"
            }
         ],
         "name":"FeesUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"newOwner",
               "type":"address"
            }
         ],
         "name":"OwnerUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"lpToken",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"gauge",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"token",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"rewardPool",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"stash",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"pid",
               "type":"uint256"
            }
         ],
         "name":"PoolAdded",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"newPoolManager",
               "type":"address"
            }
         ],
         "name":"PoolManagerUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"poolId",
               "type":"uint256"
            }
         ],
         "name":"PoolShutdown",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"lockRewards",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"address",
               "name":"stakerRewards",
               "type":"address"
            }
         ],
         "name":"RewardContractsUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"newTreasury",
               "type":"address"
            }
         ],
         "name":"TreasuryUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"address",
               "name":"newVoteDelegate",
               "type":"address"
            }
         ],
         "name":"VoteDelegateUpdated",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"user",
               "type":"address"
            },
            {
               "indexed":true,
               "internalType":"uint256",
               "name":"poolid",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"Withdrawn",
         "type":"event"
      },
      {
         "inputs":[
            
         ],
         "name":"FEE_DENOMINATOR",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"MaxFees",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"REWARD_MULTIPLIER_DENOMINATOR",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_lptoken",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_gauge",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"_stashVersion",
               "type":"uint256"
            }
         ],
         "name":"addPool",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"bridgeDelegate",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"_gauge",
               "type":"address"
            }
         ],
         "name":"claimRewards",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"crv",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            },
            {
               "internalType":"bool",
               "name":"_stake",
               "type":"bool"
            }
         ],
         "name":"deposit",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            },
            {
               "internalType":"bool",
               "name":"_stake",
               "type":"bool"
            }
         ],
         "name":"depositAll",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"distributeL2Fees",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_feeToken",
               "type":"address"
            }
         ],
         "name":"earmarkFees",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"earmarkIncentive",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            }
         ],
         "name":"earmarkRewards",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"feeManager",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "name":"feeTokens",
         "outputs":[
            {
               "internalType":"address",
               "name":"distro",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"rewards",
               "type":"address"
            },
            {
               "internalType":"bool",
               "name":"active",
               "type":"bool"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "name":"gaugeMap",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "name":"getRewardMultipliers",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"isShutdown",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"l2FeesHistory",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"lockIncentive",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"lockRewards",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"minter",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"owner",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"platformFee",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"poolInfo",
         "outputs":[
            {
               "internalType":"address",
               "name":"lptoken",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"token",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"gauge",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"crvRewards",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"stash",
               "type":"address"
            },
            {
               "internalType":"bool",
               "name":"shutdown",
               "type":"bool"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"poolLength",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"poolManager",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardArbitrator",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"_address",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"rewardClaimed",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardFactory",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_arb",
               "type":"address"
            }
         ],
         "name":"setArbitrator",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_bridgeDelegate",
               "type":"address"
            }
         ],
         "name":"setBridgeDelegate",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_delegateContract",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_delegate",
               "type":"address"
            },
            {
               "internalType":"bytes32",
               "name":"_space",
               "type":"bytes32"
            }
         ],
         "name":"setDelegate",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_rfactory",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_sfactory",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_tfactory",
               "type":"address"
            }
         ],
         "name":"setFactories",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_feeToken",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_feeDistro",
               "type":"address"
            }
         ],
         "name":"setFeeInfo",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_feeM",
               "type":"address"
            }
         ],
         "name":"setFeeManager",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_lockFees",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_stakerFees",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_callerFees",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_platform",
               "type":"uint256"
            }
         ],
         "name":"setFees",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            }
         ],
         "name":"setGaugeRedirect",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_owner",
               "type":"address"
            }
         ],
         "name":"setOwner",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_poolM",
               "type":"address"
            }
         ],
         "name":"setPoolManager",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_rewards",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_stakerRewards",
               "type":"address"
            }
         ],
         "name":"setRewardContracts",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"rewardContract",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"multiplier",
               "type":"uint256"
            }
         ],
         "name":"setRewardMultiplier",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_treasury",
               "type":"address"
            }
         ],
         "name":"setTreasury",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"bytes32",
               "name":"_hash",
               "type":"bytes32"
            }
         ],
         "name":"setVote",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_voteDelegate",
               "type":"address"
            }
         ],
         "name":"setVoteDelegate",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            }
         ],
         "name":"shutdownPool",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"shutdownSystem",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"staker",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"stakerIncentive",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"stakerRewards",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"stashFactory",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"tokenFactory",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"treasury",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_feeToken",
               "type":"address"
            },
            {
               "internalType":"bool",
               "name":"_active",
               "type":"bool"
            }
         ],
         "name":"updateFeeInfo",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_voteId",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"_votingAddress",
               "type":"address"
            },
            {
               "internalType":"bool",
               "name":"_support",
               "type":"bool"
            }
         ],
         "name":"vote",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"voteDelegate",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address[]",
               "name":"_gauge",
               "type":"address[]"
            },
            {
               "internalType":"uint256[]",
               "name":"_weight",
               "type":"uint256[]"
            }
         ],
         "name":"voteGaugeWeight",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"voteOwnership",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"voteParameter",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"withdraw",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            }
         ],
         "name":"withdrawAll",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_pid",
               "type":"uint256"
            },
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"_to",
               "type":"address"
            }
         ],
         "name":"withdrawTo",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      }
   ],
   stakingABI: [
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"pid_",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"stakingToken_",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"rewardToken_",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"operator_",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"rewardManager_",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"lptoken_",
               "type":"address"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"constructor"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"owner",
               "type":"address"
            },
            {
               "indexed":true,
               "internalType":"address",
               "name":"spender",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"value",
               "type":"uint256"
            }
         ],
         "name":"Approval",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"caller",
               "type":"address"
            },
            {
               "indexed":true,
               "internalType":"address",
               "name":"owner",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"assets",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"shares",
               "type":"uint256"
            }
         ],
         "name":"Deposit",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"reward",
               "type":"uint256"
            }
         ],
         "name":"RewardAdded",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"user",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"reward",
               "type":"uint256"
            }
         ],
         "name":"RewardPaid",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"user",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"Staked",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"from",
               "type":"address"
            },
            {
               "indexed":true,
               "internalType":"address",
               "name":"to",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"value",
               "type":"uint256"
            }
         ],
         "name":"Transfer",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"caller",
               "type":"address"
            },
            {
               "indexed":true,
               "internalType":"address",
               "name":"receiver",
               "type":"address"
            },
            {
               "indexed":true,
               "internalType":"address",
               "name":"owner",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"assets",
               "type":"uint256"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"shares",
               "type":"uint256"
            }
         ],
         "name":"Withdraw",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"user",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"Withdrawn",
         "type":"event"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_reward",
               "type":"address"
            }
         ],
         "name":"addExtraReward",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"owner",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"spender",
               "type":"address"
            }
         ],
         "name":"allowance",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"spender",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"approve",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"asset",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"account",
               "type":"address"
            }
         ],
         "name":"balanceOf",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"clearExtraRewards",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"shares",
               "type":"uint256"
            }
         ],
         "name":"convertToAssets",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"assets",
               "type":"uint256"
            }
         ],
         "name":"convertToShares",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"currentRewards",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"decimals",
         "outputs":[
            {
               "internalType":"uint8",
               "name":"",
               "type":"uint8"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"assets",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"receiver",
               "type":"address"
            }
         ],
         "name":"deposit",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"duration",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"account",
               "type":"address"
            }
         ],
         "name":"earned",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"extraRewards",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"extraRewardsLength",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"getReward",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_account",
               "type":"address"
            },
            {
               "internalType":"bool",
               "name":"_claimExtras",
               "type":"bool"
            }
         ],
         "name":"getReward",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"historicalRewards",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"lastTimeRewardApplicable",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"lastUpdateTime",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "name":"maxDeposit",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"owner",
               "type":"address"
            }
         ],
         "name":"maxMint",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"owner",
               "type":"address"
            }
         ],
         "name":"maxRedeem",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"owner",
               "type":"address"
            }
         ],
         "name":"maxWithdraw",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"shares",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"receiver",
               "type":"address"
            }
         ],
         "name":"mint",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"name",
         "outputs":[
            {
               "internalType":"string",
               "name":"",
               "type":"string"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"newRewardRatio",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"operator",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"periodFinish",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"pid",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"assets",
               "type":"uint256"
            }
         ],
         "name":"previewDeposit",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"shares",
               "type":"uint256"
            }
         ],
         "name":"previewMint",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"shares",
               "type":"uint256"
            }
         ],
         "name":"previewRedeem",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"assets",
               "type":"uint256"
            }
         ],
         "name":"previewWithdraw",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"shares",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"processIdleRewards",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_rewards",
               "type":"uint256"
            }
         ],
         "name":"queueNewRewards",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"queuedRewards",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"shares",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"receiver",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"owner",
               "type":"address"
            }
         ],
         "name":"redeem",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardManager",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardPerToken",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardPerTokenStored",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardRate",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardToken",
         "outputs":[
            {
               "internalType":"contract IERC20",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "name":"rewards",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"stake",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"stakeAll",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_for",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"stakeFor",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"stakingToken",
         "outputs":[
            {
               "internalType":"contract IERC20",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"symbol",
         "outputs":[
            {
               "internalType":"string",
               "name":"",
               "type":"string"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"totalAssets",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"totalSupply",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"transfer",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "name":"transferFrom",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "name":"userRewardPerTokenPaid",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            },
            {
               "internalType":"bool",
               "name":"claim",
               "type":"bool"
            }
         ],
         "name":"withdraw",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"assets",
               "type":"uint256"
            },
            {
               "internalType":"address",
               "name":"receiver",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"owner",
               "type":"address"
            }
         ],
         "name":"withdraw",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"bool",
               "name":"claim",
               "type":"bool"
            }
         ],
         "name":"withdrawAll",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"bool",
               "name":"claim",
               "type":"bool"
            }
         ],
         "name":"withdrawAllAndUnwrap",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            },
            {
               "internalType":"bool",
               "name":"claim",
               "type":"bool"
            }
         ],
         "name":"withdrawAndUnwrap",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      }
   ],
   miningABI: [
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"convertCrvToCvx",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"cvx",
         "outputs":[
            {
               "internalType":"contract ICvx",
               "name":"",
               "type":"ICvx"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      }
   ],
   virtualBalanceRewardPoolABI: [
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"deposit_",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"reward_",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"op_",
               "type":"address"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"constructor"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"reward",
               "type":"uint256"
            }
         ],
         "name":"RewardAdded",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"user",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"reward",
               "type":"uint256"
            }
         ],
         "name":"RewardPaid",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"user",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"Staked",
         "type":"event"
      },
      {
         "anonymous":false,
         "inputs":[
            {
               "indexed":true,
               "internalType":"address",
               "name":"user",
               "type":"address"
            },
            {
               "indexed":false,
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"Withdrawn",
         "type":"event"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"account",
               "type":"address"
            }
         ],
         "name":"balanceOf",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"currentRewards",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"deposits",
         "outputs":[
            {
               "internalType":"contract IDeposit",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"donate",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"duration",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"account",
               "type":"address"
            }
         ],
         "name":"earned",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"getReward",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_account",
               "type":"address"
            }
         ],
         "name":"getReward",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"historicalRewards",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"lastTimeRewardApplicable",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"lastUpdateTime",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"newRewardRatio",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"operator",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"periodFinish",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_rewards",
               "type":"uint256"
            }
         ],
         "name":"queueNewRewards",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"queuedRewards",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardPerToken",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardPerTokenStored",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardRate",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardToken",
         "outputs":[
            {
               "internalType":"contract IERC20",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "name":"rewards",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_account",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"stake",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"totalSupply",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "name":"userRewardPerTokenPaid",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_account",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"amount",
               "type":"uint256"
            }
         ],
         "name":"withdraw",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      }
   ],
   stashTokenABI: [
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_stash",
               "type":"address"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"constructor"
      },
      {
         "inputs":[
            
         ],
         "name":"MAX_TOTAL_SUPPLY",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"baseToken",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_operator",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_rewardPool",
               "type":"address"
            },
            {
               "internalType":"address",
               "name":"_baseToken",
               "type":"address"
            }
         ],
         "name":"init",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"isImplementation",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"isValid",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"mint",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"name",
         "outputs":[
            {
               "internalType":"string",
               "name":"",
               "type":"string"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"operator",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"rewardPool",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"bool",
               "name":"_isValid",
               "type":"bool"
            }
         ],
         "name":"setIsValid",
         "outputs":[
            
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"stash",
         "outputs":[
            {
               "internalType":"address",
               "name":"",
               "type":"address"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"symbol",
         "outputs":[
            {
               "internalType":"string",
               "name":"",
               "type":"string"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            
         ],
         "name":"totalSupply",
         "outputs":[
            {
               "internalType":"uint256",
               "name":"",
               "type":"uint256"
            }
         ],
         "stateMutability":"view",
         "type":"function"
      },
      {
         "inputs":[
            {
               "internalType":"address",
               "name":"_to",
               "type":"address"
            },
            {
               "internalType":"uint256",
               "name":"_amount",
               "type":"uint256"
            }
         ],
         "name":"transfer",
         "outputs":[
            {
               "internalType":"bool",
               "name":"",
               "type":"bool"
            }
         ],
         "stateMutability":"nonpayable",
         "type":"function"
      }
   ]
}